gazebo_ros_control/pid_gains:
  # VALUES ARE NOT CORRECT!
  # They're from iiwa_control/config/iiwa_control.yaml
  # iiwa_joint_1:  {p: 700,  i: 0.01, d: 100}

  # iiwa_joint_2:  {p: 1000,  i: 50, d: 10}

  # iiwa_joint_3: {p: 4500,  i: 35, d: 1}

  # iiwa_joint_4:  {p: 5000,  i: 60, d: 2}

  # iiwa_joint_5: {p: 1000,  i: 30, d: 0.01}

  # iiwa_joint_6:  {p: 500,  i: 0.1, d: 0.01}

  # iiwa_joint_7: {p: 100,  i: 0.1, d: 0.01}
  iiwa_joint_1:  {p: 0.07,  i: 1.0, d: 100}

  iiwa_joint_2:  {p: 0.10,  i: 5.0, d: 10}

  iiwa_joint_3: {p: 0.45,  i: 3.5, d: 1}

  iiwa_joint_4:  {p: 0.5,  i: 6, d: 2}

  iiwa_joint_5: {p: 0.1,  i: 30, d: 0.01}

  iiwa_joint_6:  {p: 0.5,  i: 0.1, d: 0.01}

  iiwa_joint_7: {p: 0.1,  i: 0.1, d: 0.01}